[programs.localnet]
messengerapp = "8a7V1HAeci2HUB1HkaCqgZsfFtjs1XGr9b2Ni8AgDeMa"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/noahchristian/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
